name: Django CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres5261285
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.11.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate
      env:
        DATABASE_URL: postgres://postgres:postgres5261285@localhost:5432/postgres


    - name: Run Tests
      run: python manage.py test
      env:
        DATABASE_URL: postgres://postgres:postgres5261285@localhost:5432/postgres

    


